#!/bin/sh 
PROJECT_PATH=.
JAR_PATH=$PROJECT_PATH/libs
BIN_PATH=$PROJECT_PATH/bin
CLASS_PATH=$PROJECT_PATH/src

echo $JAR_PATH
javac -g -nowarn -cp $CLASS_PATH -d $BIN_PATH -extdirs $JAR_PATH $CLASS_PATH/mains/TopicModelMain.java
