#!/bin/sh
#tune lambda
for k in 0.2 0.4 0.6 0.8 1.0 1.2 1.4 1.6 
	do	./run -vf ./data/Features/fv_2gram_tablets_86jsons.txt -s SEMI -cs 5 -lmd4l2r $k ./data/amazon/small/dedup/RawData | tee LambdaRank_Lambda"$k".output
done 
#tune step size
for k in 1.0 0.1 0.01 0.001 0.0001 
	do	./run -vf ./data/Features/fv_2gram_tablets_86jsons.txt -s SEMI -cs 5 -step $k ./data/amazon/small/dedup/RawData | tee LambdaRank_StepSize"$k".output
done 
#tune max iteration
for k in 100 200 300 400 500 600 
	do	./run -vf ./data/Features/fv_2gram_tablets_86jsons.txt -s SEMI -cs 5 -maxIter $k ./data/amazon/small/dedup/RawData | tee LambdaRank_MaxIteration"$k".output
done 
#tune shrinkage
for k in 0.98 0.96 0.94 0.92 0.9 0.88 
	do	./run -vf ./data/Features/fv_2gram_tablets_86jsons.txt -s SEMI -cs 5 -sk $k ./data/amazon/small/dedup/RawData | tee LambdaRank_Shrinkage"$k".output
done 
#tune window size 
for k in 0 20 40 60 80 100 120 140 
	do	./run -vf ./data/Features/fv_2gram_tablets_86jsons.txt -s SEMI -cs 5 -window $k ./data/amazon/small/dedup/RawData | tee LambdaRank_WindowSize"$k".output
done 
