#!/bin/sh
java -cp bin:libs/colt.jav:libs/concurrent.jar:libs/jsoup-1.7.3.jar:libs/jwnl-1.3.3.jar:libs/libsvm.jar:libs/opennlp-maxent-3.0.3.jar:libs/opennlp-tools-1.5.3.jar Classifier.AmazonReviewMain
