#!/bin/sh
nohup ./run -model mtclinmmb -prefix ./data/CoLinAdapt -rho 0.0001 -alpha 0.01 > ./data/1017mtclinmmb_yelp_1k_lm_1000_alpha_0.01_rho_0.0001.output &
nohup ./run -model mtclinmmb -prefix ./data/CoLinAdapt -rho 0.001 -alpha 0.01 > ./data/1017mtclinmmb_yelp_1k_lm_1000_alpha_0.01_rho_0.001.output &
nohup ./run -model mtclinmmb -prefix ./data/CoLinAdapt -rho 0.005 -alpha 0.01 > ./data/1017mtclinmmb_yelp_1k_lm_1000_alpha_0.01_rho_0.005.output &
nohup ./run -model mtclinmmb -prefix ./data/CoLinAdapt -rho 0.01 -alpha 0.01 > ./data/1017mtclinmmb_yelp_1k_lm_1000_alpha_0.01_rho_0.01.output &
nohup ./run -model mtclinmmb -prefix ./data/CoLinAdapt -rho 0.05 -alpha 0.01 > ./data/1017mtclinmmb_yelp_1k_lm_1000_alpha_0.01_rho_0.05.output &
