#!/bin/sh
nohup ./run -topicmodel CTM -nuOfTopics 5 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_5.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 10 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_10.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 15 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_15.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 20 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_20.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 25 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_25.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 30 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_30.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 35 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_35.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 40 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_40.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 45 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_45.output 2>&1 &
nohup ./run -topicmodel CTM -nuOfTopics 50 -source yelp -emIter 30 -set byUser_70k_review -flagColdstart true > ./output/yelp_70k_CTM_50.output 2>&1 &
