#!/bin/sh
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 5 > ./output/yelp_4k_CTM_5.output 2>&1 &
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 10 > ./output/yelp_4k_CTM_10.output 2>&1 &
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 15 > ./output/yelp_4k_CTM_15.output 2>&1 &
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 20 > ./output/yelp_4k_CTM_20.output 2>&1 &
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 25 > ./output/yelp_4k_CTM_25.output 2>&1 &
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 30 > ./output/yelp_4k_CTM_30.output 2>&1 &
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 35 > ./output/yelp_4k_CTM_35.output 2>&1 &
nohup ./run -set byUser_4k_review -topicmodel CTM -nuOfTopics 40 > ./output/yelp_4k_CTM_40.output 2>&1 &

