#!/bin/sh
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 10 > ./output/yelp_70k_CTM_10.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 20 > ./output/yelp_70k_CTM_20.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 30 > ./output/yelp_70k_CTM_30.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 40 > ./output/yelp_70k_CTM_40.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 50 > ./output/yelp_70k_CTM_50.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 60 > ./output/yelp_70k_CTM_60.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 70 > ./output/yelp_70k_CTM_70.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 80 > ./output/yelp_70k_CTM_80.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 90 > ./output/yelp_70k_CTM_90.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel CTM -nuOfTopics 100 > ./output/yelp_70k_CTM_100.output 2>&1 &
