#!/bin/sh

nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 10 > ./output/yelp_70k_ETBIR_10.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 20 > ./output/yelp_70k_ETBIR_20.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 30 > ./output/yelp_70k_ETBIR_30.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 40 > ./output/yelp_70k_ETBIR_40.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 50 > ./output/yelp_70k_ETBIR_50.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 60 > ./output/yelp_70k_ETBIR_60.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 70 > ./output/yelp_70k_ETBIR_70.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 80 > ./output/yelp_70k_ETBIR_80.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 90 > ./output/yelp_70k_ETBIR_90.output 2>&1 &
nohup ./run -set byUser_70k_review -topicmodel ETBIR -nuOfTopics 100 > ./output/yelp_70k_ETBIR_100.output 2>&1 &